### ISSUE TITLE
Crash in BleDisClient.readDisInfoWithKeysAsStrings

### ISSUE THREAD

**Issue by korzonkiee** [polarofficial/polar-ble-sdk#503] opened 2024-11-19 13:19 UTC
**Platform on which you observed the bug:** 
- [ ] Android 
- [x] iOS
- [ ] Other
- [ ] Platform is not relevant for this bug

**Device on which you observed the bug:**
- [ ] Polar OH1
- [ ] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [x] Device is not relevant for this bug

**Describe the bug**
App randomly crashes for some of our users. Looking at the crash report, it seems that it is a null-reference exception, where `self` is null. Most likely can be fixed by using `weak self` and doing a null-check before accessing `self`.

**How to Reproduce**
No clear reproduction steps, it happens randomly.

**Expected behavior**
App should not crash. 

**Screenshots and logs**
![CleanShot 2024-11-19 at 14 53 52@2x](https://github.com/user-attachments/assets/fbba7214-f889-481b-a979-dceb3f495cec)

**Comment by pth-pe-gh** [comment] 2024-12-13 13:56
Looking at the screen shot in the report, this may have been caused by non-thread safe access to dictionary; as the problem seems to happen on getting dictionary key values count. The proposed fix may not be enough to prevent such crash; if it is, it may cause some other functionality to fail. 

Need to check how the dictionary is accessed to see if/when access to dictionary happens from multiple threads (e.g. from different queues)

**Comment by pth-pe-gh** [comment] 2024-12-16 08:12
Will make update to SDK to fix related multithreading issue with dictionary.

**Comment by pth-pe-gh** [comment] 2024-12-18 06:04
Change to synchronise dictionary access will be in next SDK release.

**Closed by pth-pe-gh** 2024-12-18 06:04 UTC
Labels: bug
