### ISSUE TITLE
problem with disconnect Polar H10 and OH1 on iOS

### ISSUE THREAD

**Issue by avik-efcom** [polarofficial/polar-ble-sdk#190] opened 2021-09-12 09:18 UTC
**Platform on which you observed the bug:** 
- [ ] Android 
- [X] iOS
- [ ] Other
- [ ] Platform is not relevant for this bug

**Device on which you observed the bug:**
- [X] Polar OH1
- [ ] Polar Verity Sense
- [X] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this bug

**Describe the bug**
Hi, 
when I initiate disconnect from the devices it works, but if the device is disconnect (long-distance or turns off(OH1)), the function "devcieDisconected" is not called.
I try to put a print command on disconnect but it never shows
I don't use the auto-connect function so I turn it off
![image](https://user-images.githubusercontent.com/72505851/132982044-786dd4a3-1c58-4ae9-ad94-669babcd486b.png)

when I try to read the exercise list I got this error
![image](https://user-images.githubusercontent.com/72505851/132982220-0183c40b-030d-412a-978f-6c8d47461960.png)

**How to Reproduce**
only connect and disconnect by long-distance or turn the device off and the function should be called

**Expected behavior**
the function "devcieDisconected" should call after the device disconnected

**Screenshots and logs**
![image](https://user-images.githubusercontent.com/72505851/132981899-d63d8d3e-5d17-45e1-a822-3907adad05eb.png)
on the log, you can see the HR notification stop but the function deviceDisconnected not called
![image](https://user-images.githubusercontent.com/72505851/132981956-8833d9dd-026e-4b56-8a4b-111214eb10e1.png)

thanks very much

**Comment by JOikarinen** [comment] 2021-09-13 09:11
Hi @avik-efcom,

I tried to reproduce the bug you explained. I took the [example app](https://github.com/polarofficial/polar-ble-sdk/tree/master/examples/example-ios/iosBleSdkTestApp) and tried these steps with OH1 and H10:

STEPS:
1. Connect to OH1 
2. Pressed OH1 button to shut it down
3. Followed the console logs to see whether `deviceDisconnected` callback is called

OBSERVATION:
- 2021-09-13 12:04:52.792808+0300 iosBleSdkTestApp[1625:1323635] DISCONNECTED: (deviceId: "58A0EB20", address: 47D0734A-A5CB-58D9-39DE-B5527DCDC576, rssi: -55, name: "Polar OH1 58A0EB20", connectable: true)

STEPS:
1. Connect to H10 
2. H10 goes out of range
3. Followed the console logs to see whether `deviceDisconnected` callback is called

OBSERVATION:
-  2021-09-13 12:02:35.400766+0300 iosBleSdkTestApp[1621:1322550] DISCONNECTED: (deviceId: "3D474722", address: 1E1B9E05-0755-7911-A1CC-C7A24E5E2B76, rssi: -70, name: "Polar H10 3D474722", connectable: true)

Could you double check you have registered the PolarBleApiObserver for the PolarBleSDK?  Done like this in the [example ](https://github.com/polarofficial/polar-ble-sdk/blob/1585e1de6572d59fe6378830b0764375c912b676/examples/example-ios/iosBleSdkTestApp/iosBleSdkTestApp/PolarBleSdkManager.swift#L62) code: ``` api.observer = self```

**Comment by avik-efcom** [comment] 2021-09-13 10:04
![image](https://user-images.githubusercontent.com/72505851/133060442-2738ba56-1e6b-44de-a69f-b1d9b9837fd7.png)

I add now all the api-self functions from the example 
![image](https://user-images.githubusercontent.com/72505851/133065080-4675a4f9-3fa2-492e-b5de-574c50a128bb.png)

the connected function works ok
I attach the full log
deviceConnecting (deviceId: "80919F24", address: EC247EE7-23B4-4C7C-4C22-3A58F4FAC340, rssi: -20, name: "Polar OH1 80919F24", connectable: true)
deviceConnected (deviceId: "80919F24", address: EC247EE7-23B4-4C7C-4C22-3A58F4FAC340, rssi: -20, name: "Polar OH1 80919F24", connectable: true)
HR READY
battery level updated: 100
HR notification: 90 rrs: []
Feature acc is ready.
Feature ppg is ready.
Feature ppi is ready.
HR notification: 90 rrs: []
HR notification: 90 rrs: []
OP: list exercises completed
HR notification: 89 rrs: []
HR notification: 90 rrs: []
HR notification: 90 rrs: []
HR notification: 90 rrs: []
HR notification: 90 rrs: []
HR notification: 90 rrs: []
HR notification: 89 rrs: []
HR notification: 89 rrs: []
HR notification: 88 rrs: []
HR notification: 88 rrs: []
**//turn off the OH1 here**
HR notification: 0 rrs: []
**//suppost to get the disconnected print**
**//after a while ask for the exercise list (I did not know the device is disconnected from the code)**
failed to list exercises: PolarBleSdk.DeviceNotConnected

![image](https://user-images.githubusercontent.com/72505851/133063670-7973feb4-0fa2-497b-b6f1-3a29a354c271.png)

**Comment by avik-efcom** [comment] 2021-09-13 10:19
I add the logger and got this
![image](https://user-images.githubusercontent.com/72505851/133066978-ad52379a-7c83-4dd0-a0d4-52eb60d8bbb4.png)

it seems is the device disconnected but I don't know why I did not get it from the deviceDisconnected function

**Comment by NiwreRelbag** [comment] 2021-12-03 09:18
Hello,
I have a similar problem with the H10 (on iOS).
"deviceConnected" is called, but if I remove the H10 from the strap and wait a few minutes, "deviceDisconnected" is never called (and it continues to send ECG data).

When I use the H10 with the Std. CBCentralManager class, "didDisconnectPeripheral" is called about 1 minute after removing the H10 from the strap.

Thanks a lot!

**Comment by JOikarinen** [comment] 2021-12-07 11:54
@NiwreRelbag and @avik-efcom I think I found the root cause for the problem. As you described the ```deviceDisconnected``` was never called if the ```automaticReconnection``` was set to false.  The problem is now fixed in release 3.2.5

**Closed by JOikarinen** 2021-12-07 11:54 UTC
Labels: bug
