### ISSUE TITLE
Getting UndeliverableException on Android

### ISSUE THREAD

**Issue by orestesgaolin** [polarofficial/polar-ble-sdk#315] opened 2022-11-14 20:40 UTC
**Platform on which you observed the bug:** 
- [x] Android 
- [ ] iOS
- [ ] Other
- [ ] Platform is not relevant for this bug

**Device on which you observed the bug:**
- [ ] Polar OH1
- [x] Polar Verity Sense
- [ ] Polar H10
- [ ] Polar H9
- [ ] Other
- [ ] Device is not relevant for this bug

**Describe the bug**

Recently started receiving following exceptions:

```
E/AndroidRuntime(19989): FATAL EXCEPTION: RxCachedThreadScheduler-5
E/AndroidRuntime(19989): Process: [REDACTED], PID: 19989
E/AndroidRuntime(19989): io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.polar.androidcommunications.api.ble.exceptions.BleDisconnected
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryAddThrowableOrReport(AtomicThrowable.java:52)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:564)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:636)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onError(SingleToFlowable.java:68)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.internal.operators.single.SingleDelayWithCompletable$OtherObserver.onError(SingleDelayWithCompletable.java:64)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onError(CompletableAndThenCompletable.java:62)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:91)
E/AndroidRuntime(19989): 	at com.polar.androidcommunications.api.ble.model.gatt.BleGattBase.lambda$waitNotificationEnabled$1$com-polar-androidcommunications-api-ble-model-gatt-BleGattBase(BleGattBase.java:417)
E/AndroidRuntime(19989): 	at com.polar.androidcommunications.api.ble.model.gatt.BleGattBase$$ExternalSyntheticLambda1.subscribe(Unknown Source:6)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
E/AndroidRuntime(19989): 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
E/AndroidRuntime(19989): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/AndroidRuntime(19989): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
E/AndroidRuntime(19989): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime(19989): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime(19989): 	at java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime(19989): Caused by: com.polar.androidcommunications.api.ble.exceptions.BleDisconnected
E/AndroidRuntime(19989): 	at com.polar.androidcommunications.api.ble.model.gatt.BleGattBase.lambda$waitNotificationEnabled$1$com-polar-androidcommunications-api-ble-model-gatt-BleGattBase(BleGattBase.java:404)
E/AndroidRuntime(19989): 	... 12 more
```

```
Fatal Exception: de.f: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | qb.c
       at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:19)
       at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryAddThrowableOrReport(AtomicThrowable.java:8)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.innerError(FlowableFlatMap.java:2)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onError(FlowableFlatMap.java:7)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromCompletable$FromCompletableObserver.onError(FlowableFromCompletable.java:6)
       at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:46)
       at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:2)
       at io.reactivex.rxjava3.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onError(CompletableConcatArray.java:2)
       at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:2)
       at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:26)
       at com.polar.androidcommunications.api.ble.model.gatt.BleGattBase.lambda$waitNotificationEnabled$1(BleGattBase.java:110)
       at com.polar.androidcommunications.api.ble.model.gatt.BleGattBase.$r8$lambda$ByR2Ec3Uwpj0-9pA6N6PFo9QlWo(BleGattBase.java)
       at com.polar.androidcommunications.api.ble.model.gatt.BleGattBase$$InternalSyntheticLambda$5$5c9735ee6bf1983bf280d4e2028e6fe68aaa01a9b8a95e8f5c799d92419e1d0d$0.subscribe(BleGattBase.java:6)
       at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:10)
       at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:14)
       at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:2)
       at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:9)
       at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:13)
       at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

```
Caused by qb.c:
       at com.polar.androidcommunications.api.ble.model.gatt.BleGattBase.lambda$waitNotificationEnabled$1(BleGattBase.java:75)
       at com.polar.androidcommunications.api.ble.model.gatt.BleGattBase.$r8$lambda$ByR2Ec3Uwpj0-9pA6N6PFo9QlWo(BleGattBase.java)
       at com.polar.androidcommunications.api.ble.model.gatt.BleGattBase$$InternalSyntheticLambda$5$5c9735ee6bf1983bf280d4e2028e6fe68aaa01a9b8a95e8f5c799d92419e1d0d$0.subscribe(BleGattBase.java:6)
       at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:10)
       at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:14)
       at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:2)
       at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:9)
       at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:13)
       at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**How to Reproduce**

Happy to provide more detailed logs, but I was not able to reproduce reliably. The devices that it happens to include:

- OnePlus Nord Android 11
- Galaxy A12 Android 12
- Pixel 3a XL Android 12
- OnePlus 7T Android 11
- Nokia 8 Android 9
- Samsung S21 Android 13

Gradle dependencies:

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.github.polarofficial:polar-ble-sdk:3.3.2'
    implementation 'io.reactivex.rxjava3:rxjava:3.1.3'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
    implementation "androidx.startup:startup-runtime:1.1.1"
    implementation 'com.google.firebase:firebase-crashlytics:18.3.1'
}
```

Just realized that there were some updates to Android SDK and maybe it's already fixed?

**Expected behavior**

-

**Screenshots and logs**

-

**Comment by JOikarinen** [comment] 2022-11-15 05:39
Thanks for the report @orestesgaolin. This is duplicate of #300. There is one fix related on this in release [3.3.3](https://github.com/polarofficial/polar-ble-sdk/releases/tag/3.3.3), however the issue is not complete solved yet. Let's continue the discussion under #300, I will close this issue.

**Closed by JOikarinen** 2022-11-15 05:39 UTC
Labels: bug
